---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:this_week_in_cf;MODE=PostgreSQL
  jpa:
    hibernate.ddl-auto: none
    show_sql: true
  mail:
    host: localhost
    port: 2525

logging.level.org.springframework.mail: DEBUG
#logging.level.org.springframework.security: DEBUG

---
spring:
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/twicfdb
  jpa:
    hibernate.ddl-auto: verify
    show_sql: true

---
spring:
  profiles: cloud
  mail:
    host: ${vcap.services.sendgrid.credentials.hostname}
    username: ${vcap.services.sendgrid.credentials.username}
    password: ${vcap.services.sendgrid.credentials.password}